#ifndef LYNX_LWM2M_ERRORS_H
#define LYNX_LWM2M_ERRORS_H

#define OPERATION_NOT_SUPPORTED 1
#define ACCESS_RIGHT_PERMISSION_DENIED 2
#define STRANGE_ERROR 2

#define OPERATION_NOT_ALLOWED 1

#endif //LYNX_LWM2M_ERRORS_H
